"""empty message

Revision ID: 003718f82547
Revises: 0e45c0542c91
Create Date: 2025-05-22 10:16:16.799380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003718f82547'
down_revision: Union[str, None] = '0e45c0542c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint('team_car_id_fkey', 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'car', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key('team_car_id_fkey', 'team', 'car', ['car_id'], ['id'], ondelete='CASCADE')
    op.drop_column('car', 'is_deleted')
    # ### end Alembic commands ###
