"""empty message

Revision ID: 0e45c0542c91
Revises: 308e502488ab
Create Date: 2025-04-24 12:08:08.980047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0e45c0542c91'
down_revision: Union[str, None] = '308e502488ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('call_team_id_fkey', 'call', type_='foreignkey')
    op.create_foreign_key(None, 'call', 'team', ['team_id'], ['id'])

    op.add_column('team', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute("UPDATE team SET is_deleted = FALSE")
    op.alter_column("team", "is_deleted", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'is_deleted')
    op.drop_constraint(None, 'call', type_='foreignkey')
    op.create_foreign_key('call_team_id_fkey', 'call', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
