"""add refresh_id, ip to user

Revision ID: 2ca59d5037d2
Revises: a14f9989b6a2
Create Date: 2025-07-18 13:37:26.034367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca59d5037d2'
down_revision: Union[str, None] = 'a14f9989b6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ip')
    op.drop_column('user', 'refresh_id')
    # ### end Alembic commands ###
