"""add is_moving to team

Revision ID: a14f9989b6a2
Revises: 003718f82547
Create Date: 2025-07-10 10:55:43.406445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14f9989b6a2'
down_revision: Union[str, None] = '003718f82547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('is_moving', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'is_moving')
    # ### end Alembic commands ###
